name: push to pipeline github action test
on: push
jobs:
  job1: 
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: step one for first job
      uses: actions/checkout@v2 
    - name: step two for first job
      run: env | sort
  job2: 
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: step one for second job
      uses: actions/checkout@v2 
    - name: step two for second job
      run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    name: Job3 depends upon job 1 and 2
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - name: Display the current date
      run: date
    - name: print
    
    
